import { useState } from "react";
import { Activity, AlertTriangle, Banknote, Boxes, ChevronRight, IndianRupee, Coins, Gem, HandCoins, Landmark, ReceiptIndianRupee, TrendingUp } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { approvals, branches, chartData, formatINR, transactions } from "@/lib/erp-data";
import { MetricCard, PageHeader, Panel, StatusBadge } from "./ui";
import { toast } from "sonner";
const branchData=branches.map((b,i)=>({name:b.name.slice(0,3).toUpperCase(),value:Math.round(b.achieved/100000),target:Math.round(b.target/100000),fill:["var(--chart-1)","var(--chart-2)","var(--chart-3)","var(--chart-4)","var(--chart-5)"][i]}));
const tipStyle={border:"1px solid var(--border)",borderRadius:6,fontSize:12,boxShadow:"var(--shadow-card)"};
export function Dashboard(){const [period,setPeriod]=useState("month");return <><PageHeader eyebrow="Executive Overview" title="Good morning, Srinivas" description="Central operations view across 5 branches · Last refreshed today at 09:42 AM" actions={<><Select defaultValue="all"><SelectTrigger className="w-40"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All metals</SelectItem><SelectItem value="gold">Gold</SelectItem><SelectItem value="silver">Silver</SelectItem></SelectContent></Select><Tabs value={period} onValueChange={setPeriod}><TabsList><TabsTrigger value="today">Today</TabsTrigger><TabsTrigger value="week">Week</TabsTrigger><TabsTrigger value="month">Month</TabsTrigger></TabsList></Tabs></>}/>
<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4 2xl:grid-cols-5"><MetricCard label="Total Transactions" value="1,284" delta="12.4%" icon={<Activity/>}/><MetricCard label="Gold Purchased" value="4,286.72 g" delta="8.2%" icon={<Gem/>} accent/><MetricCard label="Silver Purchased" value="86.42 kg" delta="5.7%" icon={<Coins/>}/><MetricCard label="Total Purchase Value" value="₹3,84,72,600" delta="10.8%" icon={<IndianRupee/>}/><MetricCard label="Bank-Pledged Transactions" value="186" delta="3.1%" icon={<Landmark/>}/><MetricCard label="Customer Payouts" value="₹2,18,46,200" delta="9.5%" icon={<HandCoins/>}/><MetricCard label="Charges Collected" value="₹12,84,500" delta="6.4%" icon={<ReceiptIndianRupee/>}/><MetricCard label="Commission" value="₹8,42,700" delta="4.8%" icon={<Banknote/>}/><MetricCard label="Inventory Value" value="₹5,72,18,400" delta="7.9%" icon={<Boxes/>}/><MetricCard label="Expected Margin" value="₹34,86,200" delta="11.2%" icon={<TrendingUp/>} accent/></div>
<div className="mt-5 grid gap-5 xl:grid-cols-[1.45fr_1fr]"><Panel title="Purchase value trend" subtitle="Daily purchase value in lakhs"><div className="h-72 p-4"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="goldFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="var(--chart-1)" stopOpacity={.28}/><stop offset="1" stopColor="var(--chart-1)" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="day" tickLine={false} axisLine={false} fontSize={11}/><YAxis tickLine={false} axisLine={false} fontSize={11}/><Tooltip contentStyle={tipStyle}/><Area dataKey="value" stroke="var(--chart-1)" strokeWidth={2} fill="url(#goldFill)"/></AreaChart></ResponsiveContainer></div></Panel><Panel title="Branch performance" subtitle="Achieved vs monthly target · ₹ lakhs"><div className="h-72 p-4"><ResponsiveContainer width="100%" height="100%"><BarChart data={branchData}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="name" tickLine={false} axisLine={false} fontSize={11}/><YAxis tickLine={false} axisLine={false} fontSize={11}/><Tooltip contentStyle={tipStyle}/><Bar dataKey="target" fill="var(--muted)" radius={[3,3,0,0]}/><Bar dataKey="value" radius={[3,3,0,0]}>{branchData.map((x,i)=><Cell key={i} fill={x.fill}/>)}</Bar></BarChart></ResponsiveContainer></div></Panel></div>
<div className="mt-5 grid gap-5 lg:grid-cols-3"><Panel title="Gold vs Silver purchases" subtitle="Transaction mix this month"><div className="flex h-64 items-center p-4"><div className="h-full flex-1"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={[{name:"Gold",value:68},{name:"Silver",value:32}]} dataKey="value" innerRadius={55} outerRadius={78} paddingAngle={3}><Cell fill="var(--chart-1)"/><Cell fill="var(--chart-2)"/></Pie><Tooltip contentStyle={tipStyle}/></PieChart></ResponsiveContainer></div><div className="space-y-4 pr-5"><div><p className="text-xs text-muted-foreground">Gold</p><p className="font-display text-xl font-bold">68%</p></div><div><p className="text-xs text-muted-foreground">Silver</p><p className="font-display text-xl font-bold">32%</p></div></div></div></Panel><Panel title="Pending approvals" subtitle="8 requests require action" action={<Button variant="ghost" size="sm" onClick={()=>toast("Approval Center opened")}>View all<ChevronRight/></Button>}><div className="divide-y divide-border">{approvals.slice(0,4).map(a=><button key={a.id} className="flex w-full items-center gap-3 p-3 text-left hover:bg-muted/60"><div className="grid size-9 place-items-center bg-warning-muted text-warning-strong"><AlertTriangle className="size-4"/></div><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">{a.id} · {a.customerName}</p><p className="text-[11px] text-muted-foreground">{a.branch} · {formatINR(a.amount)}</p></div><span className="text-[10px] font-semibold text-warning-strong">{a.priority}</span></button>)}</div></Panel><Panel title="Operations queue" subtitle="Items needing attention"><div className="divide-y divide-border">{[["Bank payments","14","₹28.6L pending","Banknote"],["Customer settlements","9","₹12.4L pending","HandCoins"],["Inventory alerts","6","Below branch limit","Boxes"],["Testing overdue","4","Over 2 hours","Activity"]].map(([a,b,c])=><button key={a} onClick={()=>toast(`${a} queue opened`)} className="flex w-full items-center gap-3 p-3 text-left hover:bg-muted/60"><div className="grid size-9 place-items-center bg-muted text-muted-foreground"><AlertTriangle className="size-4"/></div><div className="flex-1"><p className="text-xs font-semibold">{a}</p><p className="text-[11px] text-muted-foreground">{c}</p></div><span className="font-display text-lg font-bold">{b}</span></button>)}</div></Panel></div>
<Panel className="mt-5" title="Recent transactions" subtitle="Latest activity across all branches"><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-table-head text-muted-foreground"><tr>{["Transaction","Customer","Branch","Metal","Type","Value","Status"].map(h=><th key={h} className="px-4 py-3 text-left font-semibold">{h}</th>)}</tr></thead><tbody className="divide-y divide-border">{transactions.slice(0,7).map(t=><tr key={t.id} className="hover:bg-muted/40"><td className="px-4 py-3 font-semibold text-primary">{t.id}</td><td className="px-4 py-3">{t.customerName}</td><td className="px-4 py-3 text-muted-foreground">{t.branch}</td><td className="px-4 py-3">{t.metal}</td><td className="px-4 py-3 text-muted-foreground">{t.type}</td><td className="px-4 py-3 font-semibold tabular-nums">{formatINR(t.grossMetalValue)}</td><td className="px-4 py-3"><StatusBadge value={t.status}/></td></tr>)}</tbody></table></div></Panel></>}
