/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as BankPledgedGoldRouteImport } from './routes/bank-pledged-gold'
import { Route as BankPledgedSilverRouteImport } from './routes/bank-pledged-silver'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as ChargesRouteImport } from './routes/charges'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as GoldPurchaseRouteImport } from './routes/gold-purchase'
import { Route as GoldRatesRouteImport } from './routes/gold-rates'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PacketsRouteImport } from './routes/packets'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ProfitMarginRouteImport } from './routes/profit-margin'
import { Route as ReconciliationRouteImport } from './routes/reconciliation'
import { Route as RegionsRouteImport } from './routes/regions'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SettlementsRouteImport } from './routes/settlements'
import { Route as SilverPurchaseRouteImport } from './routes/silver-purchase'
import { Route as SilverRatesRouteImport } from './routes/silver-rates'
import { Route as TestingRouteImport } from './routes/testing'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as ValuationRouteImport } from './routes/valuation'
import { Route as VaultRouteImport } from './routes/vault'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const BankPledgedGoldRoute = BankPledgedGoldRouteImport.update({
  id: '/bank-pledged-gold',
  path: '/bank-pledged-gold',
  getParentRoute: () => rootRouteImport,
} as any)
const BankPledgedSilverRoute = BankPledgedSilverRouteImport.update({
  id: '/bank-pledged-silver',
  path: '/bank-pledged-silver',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const ChargesRoute = ChargesRouteImport.update({
  id: '/charges',
  path: '/charges',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldPurchaseRoute = GoldPurchaseRouteImport.update({
  id: '/gold-purchase',
  path: '/gold-purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldRatesRoute = GoldRatesRouteImport.update({
  id: '/gold-rates',
  path: '/gold-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PacketsRoute = PacketsRouteImport.update({
  id: '/packets',
  path: '/packets',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitMarginRoute = ProfitMarginRouteImport.update({
  id: '/profit-margin',
  path: '/profit-margin',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationRoute = ReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionsRoute = RegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettlementsRoute = SettlementsRouteImport.update({
  id: '/settlements',
  path: '/settlements',
  getParentRoute: () => rootRouteImport,
} as any)
const SilverPurchaseRoute = SilverPurchaseRouteImport.update({
  id: '/silver-purchase',
  path: '/silver-purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const SilverRatesRoute = SilverRatesRouteImport.update({
  id: '/silver-rates',
  path: '/silver-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const TestingRoute = TestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const ValuationRoute = ValuationRouteImport.update({
  id: '/valuation',
  path: '/valuation',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/bank-pledged-gold': typeof BankPledgedGoldRoute
  '/bank-pledged-silver': typeof BankPledgedSilverRoute
  '/branches': typeof BranchesRoute
  '/charges': typeof ChargesRoute
  '/customers': typeof CustomersRoute
  '/employees': typeof EmployeesRoute
  '/gold-purchase': typeof GoldPurchaseRoute
  '/gold-rates': typeof GoldRatesRoute
  '/inventory': typeof InventoryRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/packets': typeof PacketsRoute
  '/payments': typeof PaymentsRoute
  '/profit-margin': typeof ProfitMarginRoute
  '/reconciliation': typeof ReconciliationRoute
  '/regions': typeof RegionsRoute
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/settlements': typeof SettlementsRoute
  '/silver-purchase': typeof SilverPurchaseRoute
  '/silver-rates': typeof SilverRatesRoute
  '/testing': typeof TestingRoute
  '/transfers': typeof TransfersRoute
  '/valuation': typeof ValuationRoute
  '/vault': typeof VaultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/bank-pledged-gold': typeof BankPledgedGoldRoute
  '/bank-pledged-silver': typeof BankPledgedSilverRoute
  '/branches': typeof BranchesRoute
  '/charges': typeof ChargesRoute
  '/customers': typeof CustomersRoute
  '/employees': typeof EmployeesRoute
  '/gold-purchase': typeof GoldPurchaseRoute
  '/gold-rates': typeof GoldRatesRoute
  '/inventory': typeof InventoryRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/packets': typeof PacketsRoute
  '/payments': typeof PaymentsRoute
  '/profit-margin': typeof ProfitMarginRoute
  '/reconciliation': typeof ReconciliationRoute
  '/regions': typeof RegionsRoute
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/settlements': typeof SettlementsRoute
  '/silver-purchase': typeof SilverPurchaseRoute
  '/silver-rates': typeof SilverRatesRoute
  '/testing': typeof TestingRoute
  '/transfers': typeof TransfersRoute
  '/valuation': typeof ValuationRoute
  '/vault': typeof VaultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/bank-pledged-gold': typeof BankPledgedGoldRoute
  '/bank-pledged-silver': typeof BankPledgedSilverRoute
  '/branches': typeof BranchesRoute
  '/charges': typeof ChargesRoute
  '/customers': typeof CustomersRoute
  '/employees': typeof EmployeesRoute
  '/gold-purchase': typeof GoldPurchaseRoute
  '/gold-rates': typeof GoldRatesRoute
  '/inventory': typeof InventoryRoute
  '/kyc': typeof KycRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/packets': typeof PacketsRoute
  '/payments': typeof PaymentsRoute
  '/profit-margin': typeof ProfitMarginRoute
  '/reconciliation': typeof ReconciliationRoute
  '/regions': typeof RegionsRoute
  '/reports': typeof ReportsRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRoute
  '/settlements': typeof SettlementsRoute
  '/silver-purchase': typeof SilverPurchaseRoute
  '/silver-rates': typeof SilverRatesRoute
  '/testing': typeof TestingRoute
  '/transfers': typeof TransfersRoute
  '/valuation': typeof ValuationRoute
  '/vault': typeof VaultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting'
    | '/analytics'
    | '/approvals'
    | '/audit-logs'
    | '/bank-pledged-gold'
    | '/bank-pledged-silver'
    | '/branches'
    | '/charges'
    | '/customers'
    | '/employees'
    | '/gold-purchase'
    | '/gold-rates'
    | '/inventory'
    | '/kyc'
    | '/login'
    | '/notifications'
    | '/packets'
    | '/payments'
    | '/profit-margin'
    | '/reconciliation'
    | '/regions'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/settlements'
    | '/silver-purchase'
    | '/silver-rates'
    | '/testing'
    | '/transfers'
    | '/valuation'
    | '/vault'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounting'
    | '/analytics'
    | '/approvals'
    | '/audit-logs'
    | '/bank-pledged-gold'
    | '/bank-pledged-silver'
    | '/branches'
    | '/charges'
    | '/customers'
    | '/employees'
    | '/gold-purchase'
    | '/gold-rates'
    | '/inventory'
    | '/kyc'
    | '/login'
    | '/notifications'
    | '/packets'
    | '/payments'
    | '/profit-margin'
    | '/reconciliation'
    | '/regions'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/settlements'
    | '/silver-purchase'
    | '/silver-rates'
    | '/testing'
    | '/transfers'
    | '/valuation'
    | '/vault'
  id:
    | '__root__'
    | '/'
    | '/accounting'
    | '/analytics'
    | '/approvals'
    | '/audit-logs'
    | '/bank-pledged-gold'
    | '/bank-pledged-silver'
    | '/branches'
    | '/charges'
    | '/customers'
    | '/employees'
    | '/gold-purchase'
    | '/gold-rates'
    | '/inventory'
    | '/kyc'
    | '/login'
    | '/notifications'
    | '/packets'
    | '/payments'
    | '/profit-margin'
    | '/reconciliation'
    | '/regions'
    | '/reports'
    | '/roles'
    | '/settings'
    | '/settlements'
    | '/silver-purchase'
    | '/silver-rates'
    | '/testing'
    | '/transfers'
    | '/valuation'
    | '/vault'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingRoute: typeof AccountingRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditLogsRoute: typeof AuditLogsRoute
  BankPledgedGoldRoute: typeof BankPledgedGoldRoute
  BankPledgedSilverRoute: typeof BankPledgedSilverRoute
  BranchesRoute: typeof BranchesRoute
  ChargesRoute: typeof ChargesRoute
  CustomersRoute: typeof CustomersRoute
  EmployeesRoute: typeof EmployeesRoute
  GoldPurchaseRoute: typeof GoldPurchaseRoute
  GoldRatesRoute: typeof GoldRatesRoute
  InventoryRoute: typeof InventoryRoute
  KycRoute: typeof KycRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PacketsRoute: typeof PacketsRoute
  PaymentsRoute: typeof PaymentsRoute
  ProfitMarginRoute: typeof ProfitMarginRoute
  ReconciliationRoute: typeof ReconciliationRoute
  RegionsRoute: typeof RegionsRoute
  ReportsRoute: typeof ReportsRoute
  RolesRoute: typeof RolesRoute
  SettingsRoute: typeof SettingsRoute
  SettlementsRoute: typeof SettlementsRoute
  SilverPurchaseRoute: typeof SilverPurchaseRoute
  SilverRatesRoute: typeof SilverRatesRoute
  TestingRoute: typeof TestingRoute
  TransfersRoute: typeof TransfersRoute
  ValuationRoute: typeof ValuationRoute
  VaultRoute: typeof VaultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-pledged-gold': {
      id: '/bank-pledged-gold'
      path: '/bank-pledged-gold'
      fullPath: '/bank-pledged-gold'
      preLoaderRoute: typeof BankPledgedGoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-pledged-silver': {
      id: '/bank-pledged-silver'
      path: '/bank-pledged-silver'
      fullPath: '/bank-pledged-silver'
      preLoaderRoute: typeof BankPledgedSilverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charges': {
      id: '/charges'
      path: '/charges'
      fullPath: '/charges'
      preLoaderRoute: typeof ChargesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold-purchase': {
      id: '/gold-purchase'
      path: '/gold-purchase'
      fullPath: '/gold-purchase'
      preLoaderRoute: typeof GoldPurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold-rates': {
      id: '/gold-rates'
      path: '/gold-rates'
      fullPath: '/gold-rates'
      preLoaderRoute: typeof GoldRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packets': {
      id: '/packets'
      path: '/packets'
      fullPath: '/packets'
      preLoaderRoute: typeof PacketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profit-margin': {
      id: '/profit-margin'
      path: '/profit-margin'
      fullPath: '/profit-margin'
      preLoaderRoute: typeof ProfitMarginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation': {
      id: '/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof ReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions': {
      id: '/regions'
      path: '/regions'
      fullPath: '/regions'
      preLoaderRoute: typeof RegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settlements': {
      id: '/settlements'
      path: '/settlements'
      fullPath: '/settlements'
      preLoaderRoute: typeof SettlementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/silver-purchase': {
      id: '/silver-purchase'
      path: '/silver-purchase'
      fullPath: '/silver-purchase'
      preLoaderRoute: typeof SilverPurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/silver-rates': {
      id: '/silver-rates'
      path: '/silver-rates'
      fullPath: '/silver-rates'
      preLoaderRoute: typeof SilverRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testing': {
      id: '/testing'
      path: '/testing'
      fullPath: '/testing'
      preLoaderRoute: typeof TestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/valuation': {
      id: '/valuation'
      path: '/valuation'
      fullPath: '/valuation'
      preLoaderRoute: typeof ValuationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingRoute: AccountingRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditLogsRoute: AuditLogsRoute,
  BankPledgedGoldRoute: BankPledgedGoldRoute,
  BankPledgedSilverRoute: BankPledgedSilverRoute,
  BranchesRoute: BranchesRoute,
  ChargesRoute: ChargesRoute,
  CustomersRoute: CustomersRoute,
  EmployeesRoute: EmployeesRoute,
  GoldPurchaseRoute: GoldPurchaseRoute,
  GoldRatesRoute: GoldRatesRoute,
  InventoryRoute: InventoryRoute,
  KycRoute: KycRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PacketsRoute: PacketsRoute,
  PaymentsRoute: PaymentsRoute,
  ProfitMarginRoute: ProfitMarginRoute,
  ReconciliationRoute: ReconciliationRoute,
  RegionsRoute: RegionsRoute,
  ReportsRoute: ReportsRoute,
  RolesRoute: RolesRoute,
  SettingsRoute: SettingsRoute,
  SettlementsRoute: SettlementsRoute,
  SilverPurchaseRoute: SilverPurchaseRoute,
  SilverRatesRoute: SilverRatesRoute,
  TestingRoute: TestingRoute,
  TransfersRoute: TransfersRoute,
  ValuationRoute: ValuationRoute,
  VaultRoute: VaultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
